using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace SchTech.Api.Manager.GracenoteOnApi.Schema.GNProgramSchema
{
    public class GnApiProgramsSchema
    {
        //
        // This source code was auto-generated by xsd, Version=4.6.1590.0.
        // 


        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        [XmlRoot(Namespace = "", IsNullable = false)]
        public class on
        {
            private header headerField;

            private List<programsProgram> programsField;

            private decimal schemaVersionField;

            public on()
            {
                schemaVersionField = 3.2m;
            }

            /// <remarks />
            public header header
            {
                get => headerField;
                set => headerField = value;
            }

            /// <remarks />
            [XmlArrayItem("program", IsNullable = false)]
            public List<programsProgram> programs
            {
                get => programsField;
                set => programsField = value;
            }

            /// <remarks />
            [XmlAttribute]
            [DefaultValue(typeof(decimal), "3.2")]
            public decimal schemaVersion
            {
                get => schemaVersionField;
                set => schemaVersionField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        [XmlRoot(Namespace = "", IsNullable = false)]
        public class header
        {
            private string contentField;

            private string copyrightField;

            private DateTime createdField;

            private List<headerRequestParameter> requestParametersField;

            private headerStreamData streamDataField;

            /// <remarks />
            public string content
            {
                get => contentField;
                set => contentField = value;
            }

            /// <remarks />
            public DateTime created
            {
                get => createdField;
                set => createdField = value;
            }

            /// <remarks />
            public string copyright
            {
                get => copyrightField;
                set => copyrightField = value;
            }

            /// <remarks />
            [XmlArrayItem("requestParameter", IsNullable = false)]
            public List<headerRequestParameter> requestParameters
            {
                get => requestParametersField;
                set => requestParametersField = value;
            }

            /// <remarks />
            public headerStreamData streamData
            {
                get => streamDataField;
                set => streamDataField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class headerRequestParameter
        {
            private string nameField;

            private string valueField;

            /// <remarks />
            [XmlAttribute]
            public string name
            {
                get => nameField;
                set => nameField = value;
            }

            /// <remarks />
            [XmlText]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        public class identifierType
        {
            private List<string> idField;

            private string typeField;

            /// <remarks />
            [XmlElement("id", DataType = "token")]
            public List<string> id
            {
                get => idField;
                set => idField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string type
            {
                get => typeField;
                set => typeField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        public class assetType
        {
            private string assetIdField;

            private List<assetTypeCaption> captionField;

            private string categoryField;

            private bool deletedField;

            private bool deletedFieldSpecified;

            private DateTime expiredDateField;

            private bool expiredDateFieldSpecified;

            private string familyIdField;

            private bool familyMasterField;

            private bool familyMasterFieldSpecified;

            private string heightField;

            private List<identifierType> identifiersField;

            private DateTime lastModifiedField;

            private bool lastModifiedFieldSpecified;

            private bool primaryField;

            private bool primaryFieldSpecified;

            private string provider1Field;

            private string providerField;

            private string ratioField;

            private string seasonIdField;

            private string tierField;

            private string typeField;

            private string updateIdField;

            private string uRIField;

            private string widthField;

            /// <remarks />
            [XmlArrayItem("identifier", IsNullable = false)]
            public List<identifierType> identifiers
            {
                get => identifiersField;
                set => identifiersField = value;
            }

            /// <remarks />
            public string URI
            {
                get => uRIField;
                set => uRIField = value;
            }

            /// <remarks />
            [XmlElement("caption")]
            public List<assetTypeCaption> caption
            {
                get => captionField;
                set => captionField = value;
            }

            /// <remarks />
            public string provider
            {
                get => providerField;
                set => providerField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string assetId
            {
                get => assetIdField;
                set => assetIdField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "nonNegativeInteger")]
            public string updateId
            {
                get => updateIdField;
                set => updateIdField = value;
            }

            /// <remarks />
            [XmlAttribute]
            public bool deleted
            {
                get => deletedField;
                set => deletedField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool deletedSpecified
            {
                get => deletedFieldSpecified;
                set => deletedFieldSpecified = value;
            }

            /// <remarks />
            [XmlAttribute]
            public DateTime lastModified
            {
                get => lastModifiedField;
                set => lastModifiedField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool lastModifiedSpecified
            {
                get => lastModifiedFieldSpecified;
                set => lastModifiedFieldSpecified = value;
            }

            /// <remarks />
            [XmlAttribute]
            public DateTime expiredDate
            {
                get => expiredDateField;
                set => expiredDateField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool expiredDateSpecified
            {
                get => expiredDateFieldSpecified;
                set => expiredDateFieldSpecified = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string type
            {
                get => typeField;
                set => typeField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string width
            {
                get => widthField;
                set => widthField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string height
            {
                get => heightField;
                set => heightField = value;
            }

            /// <remarks />
            [XmlAttribute]
            public bool primary
            {
                get => primaryField;
                set => primaryField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool primarySpecified
            {
                get => primaryFieldSpecified;
                set => primaryFieldSpecified = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string category
            {
                get => categoryField;
                set => categoryField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string ratio
            {
                get => ratioField;
                set => ratioField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string tier
            {
                get => tierField;
                set => tierField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string seasonId
            {
                get => seasonIdField;
                set => seasonIdField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string familyId
            {
                get => familyIdField;
                set => familyIdField = value;
            }

            /// <remarks />
            [XmlAttribute]
            public bool familyMaster
            {
                get => familyMasterField;
                set => familyMasterField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool familyMasterSpecified
            {
                get => familyMasterFieldSpecified;
                set => familyMasterFieldSpecified = value;
            }

            /// <remarks />
            [XmlAttribute("provider", DataType = "token")]
            public string provider1
            {
                get => provider1Field;
                set => provider1Field = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class assetTypeCaption
        {
            private string langField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "language")]
            public string lang
            {
                get => langField;
                set => langField = value;
            }

            /// <remarks />
            [XmlText]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        public class ratingType
        {
            private List<ratingTypeAdvisory> advisoriesField;

            private ratingTypeQualityRating qualityRatingField;

            private List<ratingTypeRating> ratingField;

            /// <remarks />
            [XmlArrayItem("advisory", IsNullable = false)]
            public List<ratingTypeAdvisory> advisories
            {
                get => advisoriesField;
                set => advisoriesField = value;
            }

            /// <remarks />
            [XmlElement("rating")]
            public List<ratingTypeRating> rating
            {
                get => ratingField;
                set => ratingField = value;
            }

            /// <remarks />
            public ratingTypeQualityRating qualityRating
            {
                get => qualityRatingField;
                set => qualityRatingField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class ratingTypeAdvisory
        {
            private string ratingsBodyField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string ratingsBody
            {
                get => ratingsBodyField;
                set => ratingsBodyField = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class ratingTypeRating
        {
            private string areaField;

            private string codeField;

            private string descriptionField;

            private string ratingsBodyField;

            private string warningField;

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string warning
            {
                get => warningField;
                set => warningField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string area
            {
                get => areaField;
                set => areaField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string code
            {
                get => codeField;
                set => codeField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string description
            {
                get => descriptionField;
                set => descriptionField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string ratingsBody
            {
                get => ratingsBodyField;
                set => ratingsBodyField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class ratingTypeQualityRating
        {
            private string numVotesField;

            private string ratingsBodyField;

            private float valueField;

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string ratingsBody
            {
                get => ratingsBodyField;
                set => ratingsBodyField = value;
            }

            /// <remarks />
            [XmlAttribute]
            public float value
            {
                get => valueField;
                set => valueField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "integer")]
            public string numVotes
            {
                get => numVotesField;
                set => numVotesField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        public class awardType
        {
            private awardTypeCategory categoryField;

            private awardTypeName nameField;

            private awardTypeRecipient recipientField;

            private bool wonField;

            private bool wonFieldSpecified;

            private string yearField;

            /// <remarks />
            public awardTypeName name
            {
                get => nameField;
                set => nameField = value;
            }

            /// <remarks />
            public awardTypeCategory category
            {
                get => categoryField;
                set => categoryField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "gYear")]
            public string year
            {
                get => yearField;
                set => yearField = value;
            }

            /// <remarks />
            public awardTypeRecipient recipient
            {
                get => recipientField;
                set => recipientField = value;
            }

            /// <remarks />
            [XmlAttribute]
            public bool won
            {
                get => wonField;
                set => wonField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool wonSpecified
            {
                get => wonFieldSpecified;
                set => wonFieldSpecified = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class awardTypeName
        {
            private string awardIdField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "integer")]
            public string awardId
            {
                get => awardIdField;
                set => awardIdField = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class awardTypeCategory
        {
            private string awardCatIdField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "integer")]
            public string awardCatId
            {
                get => awardCatIdField;
                set => awardCatIdField = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class awardTypeRecipient
        {
            private string nameIdField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "integer")]
            public string nameId
            {
                get => nameIdField;
                set => nameIdField = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        public class pNameType
        {
            private string firstField;

            private string lastField;

            private string middleField;

            private string prefixField;

            private string suffixField;

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string prefix
            {
                get => prefixField;
                set => prefixField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string first
            {
                get => firstField;
                set => firstField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string middle
            {
                get => middleField;
                set => middleField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string last
            {
                get => lastField;
                set => lastField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string suffix
            {
                get => suffixField;
                set => suffixField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        public class titleDescType
        {
            private string langField;

            private string sizeField;

            private string subTypeField;

            private string typeField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string size
            {
                get => sizeField;
                set => sizeField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string type
            {
                get => typeField;
                set => typeField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string subType
            {
                get => subTypeField;
                set => subTypeField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "language")]
            public string lang
            {
                get => langField;
                set => langField = value;
            }

            /// <remarks />
            [XmlText]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class headerStreamData
        {
            private long maxUpdateIdField;

            private bool maxUpdateIdFieldSpecified;

            private long nextUpdateIdField;

            private bool nextUpdateIdFieldSpecified;

            /// <remarks />
            public long nextUpdateId
            {
                get => nextUpdateIdField;
                set => nextUpdateIdField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool nextUpdateIdSpecified
            {
                get => nextUpdateIdFieldSpecified;
                set => nextUpdateIdFieldSpecified = value;
            }

            /// <remarks />
            public long maxUpdateId
            {
                get => maxUpdateIdField;
                set => maxUpdateIdField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool maxUpdateIdSpecified
            {
                get => maxUpdateIdFieldSpecified;
                set => maxUpdateIdFieldSpecified = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgram
        {
            private string animationField;

            private List<assetType> assetsField;

            private List<awardType> awardsField;

            private List<castTypeMember> castField;

            private string colorCodeField;

            private string connectorIdField;

            private List<string> countriesField;

            private List<crewTypeMember> crewField;

            private bool deletedField;

            private bool deletedFieldSpecified;

            private programsProgramDescriptions descriptionsField;

            private string durationField;

            private programsProgramEpisodeInfo episodeInfoField;

            private List<externalLinksTypeExternalLink> externalLinksField;

            private List<programsProgramGenre> genresField;

            private programsProgramHoliday holidayField;

            private bool inactiveField;

            private bool inactiveFieldSpecified;

            private List<keywordsTypeKeyword> keywordsField;

            private programsProgramLastOriginalNetwork lastOriginalNetworkField;

            private programsProgramMovieInfo movieInfoField;

            private List<string> officialURLField;

            private DateTime origAirDateField;

            private bool origAirDateFieldSpecified;

            private string origAudioLangField;

            private programsProgramOriginalNetwork originalNetworkField;

            private string partNumberField;

            private string progTypeField;

            private ratingType ratingsField;

            private List<relationsTypeRelation> relationsField;

            private List<relationshipsTypeRelationship> relationshipsField;

            private List<programsProgramRelease> releasesField;

            private string rootIdField;

            private string runTimeField;

            private string seasonIdField;

            private List<programsProgramSeason> seasonsField;

            private DateTime seriesFinaleField;

            private bool seriesFinaleFieldSpecified;

            private string seriesIdField;

            private DateTime seriesPremiereField;

            private bool seriesPremiereFieldSpecified;

            private bool showcardField;

            private bool showcardFieldSpecified;

            private string sourceTypeField;

            private programsProgramSportsInfo sportsInfoField;

            private string subTypeField;

            private programsProgramTitles titlesField;

            private string tMSIdField;

            private string totalPartsField;

            private DateTime updateDateField;

            private string updateIdField;

            private string versionIdField;

            private string versionLabelField;

            private List<videoDescriptorsTypeVideoDescriptor> videoDescriptorsField;

            /// <remarks />
            public programsProgramTitles titles
            {
                get => titlesField;
                set => titlesField = value;
            }

            /// <remarks />
            public programsProgramDescriptions descriptions
            {
                get => descriptionsField;
                set => descriptionsField = value;
            }

            /// <remarks />
            [XmlArrayItem("member", IsNullable = false)]
            public List<castTypeMember> cast
            {
                get => castField;
                set => castField = value;
            }

            /// <remarks />
            [XmlArrayItem("member", IsNullable = false)]
            public List<crewTypeMember> crew
            {
                get => crewField;
                set => crewField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "duration")]
            public string runTime
            {
                get => runTimeField;
                set => runTimeField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string progType
            {
                get => progTypeField;
                set => progTypeField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string subType
            {
                get => subTypeField;
                set => subTypeField = value;
            }

            /// <remarks />
            public programsProgramHoliday holiday
            {
                get => holidayField;
                set => holidayField = value;
            }

            /// <remarks />
            [XmlArrayItem("country", DataType = "token", IsNullable = false)]
            public List<string> countries
            {
                get => countriesField;
                set => countriesField = value;
            }

            /// <remarks />
            [XmlArrayItem("award", IsNullable = false)]
            public List<awardType> awards
            {
                get => awardsField;
                set => awardsField = value;
            }

            /// <remarks />
            [XmlArrayItem("genre", IsNullable = false)]
            public List<programsProgramGenre> genres
            {
                get => genresField;
                set => genresField = value;
            }

            /// <remarks />
            public ratingType ratings
            {
                get => ratingsField;
                set => ratingsField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "date")]
            public DateTime origAirDate
            {
                get => origAirDateField;
                set => origAirDateField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool origAirDateSpecified
            {
                get => origAirDateFieldSpecified;
                set => origAirDateFieldSpecified = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string colorCode
            {
                get => colorCodeField;
                set => colorCodeField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string versionLabel
            {
                get => versionLabelField;
                set => versionLabelField = value;
            }

            /// <remarks />
            public programsProgramMovieInfo movieInfo
            {
                get => movieInfoField;
                set => movieInfoField = value;
            }

            /// <remarks />
            public programsProgramEpisodeInfo episodeInfo
            {
                get => episodeInfoField;
                set => episodeInfoField = value;
            }

            /// <remarks />
            public programsProgramSportsInfo sportsInfo
            {
                get => sportsInfoField;
                set => sportsInfoField = value;
            }

            /// <remarks />
            [XmlArrayItem("asset", IsNullable = false)]
            public List<assetType> assets
            {
                get => assetsField;
                set => assetsField = value;
            }

            /// <remarks />
            [XmlArrayItem("release", IsNullable = false)]
            public List<programsProgramRelease> releases
            {
                get => releasesField;
                set => releasesField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string animation
            {
                get => animationField;
                set => animationField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "language")]
            public string origAudioLang
            {
                get => origAudioLangField;
                set => origAudioLangField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string sourceType
            {
                get => sourceTypeField;
                set => sourceTypeField = value;
            }

            /// <remarks />
            public programsProgramOriginalNetwork originalNetwork
            {
                get => originalNetworkField;
                set => originalNetworkField = value;
            }

            /// <remarks />
            public programsProgramLastOriginalNetwork lastOriginalNetwork
            {
                get => lastOriginalNetworkField;
                set => lastOriginalNetworkField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "date")]
            public DateTime seriesPremiere
            {
                get => seriesPremiereField;
                set => seriesPremiereField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool seriesPremiereSpecified
            {
                get => seriesPremiereFieldSpecified;
                set => seriesPremiereFieldSpecified = value;
            }

            /// <remarks />
            [XmlElement(DataType = "date")]
            public DateTime seriesFinale
            {
                get => seriesFinaleField;
                set => seriesFinaleField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool seriesFinaleSpecified
            {
                get => seriesFinaleFieldSpecified;
                set => seriesFinaleFieldSpecified = value;
            }

            /// <remarks />
            [XmlArrayItem("season", IsNullable = false)]
            public List<programsProgramSeason> seasons
            {
                get => seasonsField;
                set => seasonsField = value;
            }

            /// <remarks />
            [XmlArrayItem("keyword", IsNullable = false)]
            public List<keywordsTypeKeyword> keywords
            {
                get => keywordsField;
                set => keywordsField = value;
            }

            /// <remarks />
            [XmlArrayItem("relation", IsNullable = false)]
            public List<relationsTypeRelation> relations
            {
                get => relationsField;
                set => relationsField = value;
            }

            /// <remarks />
            [XmlArrayItem("relationship", IsNullable = false)]
            public List<relationshipsTypeRelationship> relationships
            {
                get => relationshipsField;
                set => relationshipsField = value;
            }

            /// <remarks />
            public bool showcard
            {
                get => showcardField;
                set => showcardField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool showcardSpecified
            {
                get => showcardFieldSpecified;
                set => showcardFieldSpecified = value;
            }

            /// <remarks />
            [XmlElement("officialURL", DataType = "token")]
            public List<string> officialURL
            {
                get => officialURLField;
                set => officialURLField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "positiveInteger")]
            public string partNumber
            {
                get => partNumberField;
                set => partNumberField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "positiveInteger")]
            public string totalParts
            {
                get => totalPartsField;
                set => totalPartsField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "positiveInteger")]
            public string duration
            {
                get => durationField;
                set => durationField = value;
            }

            /// <remarks />
            [XmlArrayItem("externalLink", IsNullable = false)]
            public List<externalLinksTypeExternalLink> externalLinks
            {
                get => externalLinksField;
                set => externalLinksField = value;
            }

            /// <remarks />
            [XmlArrayItem("videoDescriptor", IsNullable = false)]
            public List<videoDescriptorsTypeVideoDescriptor> videoDescriptors
            {
                get => videoDescriptorsField;
                set => videoDescriptorsField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string TMSId
            {
                get => tMSIdField;
                set => tMSIdField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string rootId
            {
                get => rootIdField;
                set => rootIdField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string versionId
            {
                get => versionIdField;
                set => versionIdField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string connectorId
            {
                get => connectorIdField;
                set => connectorIdField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string seasonId
            {
                get => seasonIdField;
                set => seasonIdField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string seriesId
            {
                get => seriesIdField;
                set => seriesIdField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "nonNegativeInteger")]
            public string updateId
            {
                get => updateIdField;
                set => updateIdField = value;
            }

            /// <remarks />
            [XmlAttribute]
            public DateTime updateDate
            {
                get => updateDateField;
                set => updateDateField = value;
            }

            /// <remarks />
            [XmlAttribute]
            public bool inactive
            {
                get => inactiveField;
                set => inactiveField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool inactiveSpecified
            {
                get => inactiveFieldSpecified;
                set => inactiveFieldSpecified = value;
            }

            /// <remarks />
            [XmlAttribute]
            public bool deleted
            {
                get => deletedField;
                set => deletedField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool deletedSpecified
            {
                get => deletedFieldSpecified;
                set => deletedFieldSpecified = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramTitles
        {
            private string langField;

            private List<titleDescType> titleField;

            /// <remarks />
            [XmlElement("title")]
            public List<titleDescType> title
            {
                get => titleField;
                set => titleField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "language")]
            public string lang
            {
                get => langField;
                set => langField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramDescriptions
        {
            private List<titleDescType> descField;

            private string langField;

            /// <remarks />
            [XmlElement("desc")]
            public List<titleDescType> desc
            {
                get => descField;
                set => descField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "language")]
            public string lang
            {
                get => langField;
                set => langField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class castTypeMember
        {
            private string characterNameField;

            private bool departedField;

            private bool departedFieldSpecified;

            private castTypeMemberName nameField;

            private string ordField;

            private string personIdField;

            private string roleField;

            /// <remarks />
            public string characterName
            {
                get => characterNameField;
                set => characterNameField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string role
            {
                get => roleField;
                set => roleField = value;
            }

            /// <remarks />
            public castTypeMemberName name
            {
                get => nameField;
                set => nameField = value;
            }

            /// <remarks />
            public bool departed
            {
                get => departedField;
                set => departedField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool departedSpecified
            {
                get => departedFieldSpecified;
                set => departedFieldSpecified = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string personId
            {
                get => personIdField;
                set => personIdField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string ord
            {
                get => ordField;
                set => ordField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class castTypeMemberName : pNameType
        {
            private string nameIdField;

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string nameId
            {
                get => nameIdField;
                set => nameIdField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class crewTypeMember
        {
            private crewTypeMemberName nameField;

            private string ordField;

            private string personIdField;

            private string roleField;

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string role
            {
                get => roleField;
                set => roleField = value;
            }

            /// <remarks />
            public crewTypeMemberName name
            {
                get => nameField;
                set => nameField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string personId
            {
                get => personIdField;
                set => personIdField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string ord
            {
                get => ordField;
                set => ordField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class crewTypeMemberName : pNameType
        {
            private string nameIdField;

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string nameId
            {
                get => nameIdField;
                set => nameIdField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramHoliday
        {
            private string holidayIdField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "integer")]
            public string holidayId
            {
                get => holidayIdField;
                set => holidayIdField = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramGenre
        {
            private string genreIdField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string genreId
            {
                get => genreIdField;
                set => genreIdField = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramMovieInfo
        {
            private List<string> pictureFormatsField;

            private List<string> productionCompaniesField;

            private List<string> soundMixesField;

            private List<programsProgramMovieInfoTrailer> trailersField;

            private string yearOfReleaseField;

            /// <remarks />
            [XmlArrayItem("soundMix", DataType = "token", IsNullable = false)]
            public List<string> soundMixes
            {
                get => soundMixesField;
                set => soundMixesField = value;
            }

            /// <remarks />
            [XmlArrayItem("pictureFormat", DataType = "token", IsNullable = false)]
            public List<string> pictureFormats
            {
                get => pictureFormatsField;
                set => pictureFormatsField = value;
            }

            /// <remarks />
            [XmlArrayItem("name", DataType = "token", IsNullable = false)]
            public List<string> productionCompanies
            {
                get => productionCompaniesField;
                set => productionCompaniesField = value;
            }

            /// <remarks />
            [XmlArrayItem("trailer", IsNullable = false)]
            public List<programsProgramMovieInfoTrailer> trailers
            {
                get => trailersField;
                set => trailersField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string yearOfRelease
            {
                get => yearOfReleaseField;
                set => yearOfReleaseField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramMovieInfoTrailer
        {
            private string formatField;

            private string uRLField;

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string format
            {
                get => formatField;
                set => formatField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string URL
            {
                get => uRLField;
                set => uRLField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramEpisodeInfo
        {
            private List<programsProgramEpisodeInfoAlternate> alternateField;

            private string altSynNumField;

            private string episodesField;

            private string numberField;

            private string numInSeriesField;

            private string seasonField;

            private string seasonYearField;

            private string synNumField;

            private titleDescType titleField;

            /// <remarks />
            public titleDescType title
            {
                get => titleField;
                set => titleField = value;
            }

            /// <remarks />
            public string synNum
            {
                get => synNumField;
                set => synNumField = value;
            }

            /// <remarks />
            [XmlElement("alternate")]
            public List<programsProgramEpisodeInfoAlternate> alternate
            {
                get => alternateField;
                set => alternateField = value;
            }

            /// <remarks />
            public string altSynNum
            {
                get => altSynNumField;
                set => altSynNumField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string season
            {
                get => seasonField;
                set => seasonField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string number
            {
                get => numberField;
                set => numberField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string episodes
            {
                get => episodesField;
                set => episodesField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string numInSeries
            {
                get => numInSeriesField;
                set => numInSeriesField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string seasonYear
            {
                get => seasonYearField;
                set => seasonYearField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramEpisodeInfoAlternate
        {
            private string countryField;

            private bool countrywideField;

            private bool countrywideFieldSpecified;

            private string episodeField;

            private long prgSvcIdField;

            private bool prgSvcIdFieldSpecified;

            private long seasonField;

            private bool seasonFieldSpecified;

            /// <remarks />
            [XmlAttribute]
            public string country
            {
                get => countryField;
                set => countryField = value;
            }

            /// <remarks />
            [XmlAttribute]
            public bool countrywide
            {
                get => countrywideField;
                set => countrywideField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool countrywideSpecified
            {
                get => countrywideFieldSpecified;
                set => countrywideFieldSpecified = value;
            }

            /// <remarks />
            [XmlAttribute]
            public long prgSvcId
            {
                get => prgSvcIdField;
                set => prgSvcIdField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool prgSvcIdSpecified
            {
                get => prgSvcIdFieldSpecified;
                set => prgSvcIdFieldSpecified = value;
            }

            /// <remarks />
            [XmlAttribute]
            public long season
            {
                get => seasonField;
                set => seasonField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool seasonSpecified
            {
                get => seasonFieldSpecified;
                set => seasonFieldSpecified = value;
            }

            /// <remarks />
            [XmlAttribute]
            public string episode
            {
                get => episodeField;
                set => episodeField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramSportsInfo
        {
            private DateTime gameDateField;

            private bool gameDateFieldSpecified;

            private DateTime gameTimeField;

            private bool gameTimeFieldSpecified;

            private string gameTimeZoneField;

            private programsProgramSportsInfoPlayoffRound playoffRoundField;

            private programsProgramSportsInfoSeason seasonField;

            private List<programsProgramSportsInfoTeam> teamField;

            private programsProgramSportsInfoVenue venueField;

            /// <remarks />
            [XmlElement(DataType = "date")]
            public DateTime gameDate
            {
                get => gameDateField;
                set => gameDateField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool gameDateSpecified
            {
                get => gameDateFieldSpecified;
                set => gameDateFieldSpecified = value;
            }

            /// <remarks />
            [XmlElement(DataType = "time")]
            public DateTime gameTime
            {
                get => gameTimeField;
                set => gameTimeField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool gameTimeSpecified
            {
                get => gameTimeFieldSpecified;
                set => gameTimeFieldSpecified = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string gameTimeZone
            {
                get => gameTimeZoneField;
                set => gameTimeZoneField = value;
            }

            /// <remarks />
            public programsProgramSportsInfoVenue venue
            {
                get => venueField;
                set => venueField = value;
            }

            /// <remarks />
            [XmlElement("team")]
            public List<programsProgramSportsInfoTeam> team
            {
                get => teamField;
                set => teamField = value;
            }

            /// <remarks />
            public programsProgramSportsInfoSeason season
            {
                get => seasonField;
                set => seasonField = value;
            }

            /// <remarks />
            public programsProgramSportsInfoPlayoffRound playoffRound
            {
                get => playoffRoundField;
                set => playoffRoundField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramSportsInfoVenue
        {
            private string valueField;

            private string venueBrandIdField;

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string venueBrandId
            {
                get => venueBrandIdField;
                set => venueBrandIdField = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramSportsInfoTeam
        {
            private bool isHomeField;

            private bool isHomeFieldSpecified;

            private string teamBrandIdField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string teamBrandId
            {
                get => teamBrandIdField;
                set => teamBrandIdField = value;
            }

            /// <remarks />
            [XmlAttribute]
            public bool isHome
            {
                get => isHomeField;
                set => isHomeField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool isHomeSpecified
            {
                get => isHomeFieldSpecified;
                set => isHomeFieldSpecified = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramSportsInfoSeason
        {
            private string typeField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string type
            {
                get => typeField;
                set => typeField = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramSportsInfoPlayoffRound
        {
            private string gameNumberField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string gameNumber
            {
                get => gameNumberField;
                set => gameNumberField = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramRelease
        {
            private List<programsProgramReleaseAttribute> attributesField;

            private string countryField;

            private string dateField;

            private List<string> distributorsField;

            private string editNotesField;

            private string mediumField;

            private string prgSvcIdField;

            private string seasonNameField;

            private string seasonYearField;

            private string typeField;

            /// <remarks />
            public string editNotes
            {
                get => editNotesField;
                set => editNotesField = value;
            }

            /// <remarks />
            [XmlArrayItem("name", DataType = "token", IsNullable = false)]
            public List<string> distributors
            {
                get => distributorsField;
                set => distributorsField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string country
            {
                get => countryField;
                set => countryField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string type
            {
                get => typeField;
                set => typeField = value;
            }

            /// <remarks />
            [XmlArrayItem("attribute", IsNullable = false)]
            public List<programsProgramReleaseAttribute> attributes
            {
                get => attributesField;
                set => attributesField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string date
            {
                get => dateField;
                set => dateField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string medium
            {
                get => mediumField;
                set => mediumField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "positiveInteger")]
            public string prgSvcId
            {
                get => prgSvcIdField;
                set => prgSvcIdField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "positiveInteger")]
            public string seasonYear
            {
                get => seasonYearField;
                set => seasonYearField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "token")]
            public string seasonName
            {
                get => seasonNameField;
                set => seasonNameField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramReleaseAttribute
        {
            private string typeField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string type
            {
                get => typeField;
                set => typeField = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramOriginalNetwork
        {
            private string prgSvcIdField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "integer")]
            public string prgSvcId
            {
                get => prgSvcIdField;
                set => prgSvcIdField = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramLastOriginalNetwork
        {
            private string prgSvcIdField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "integer")]
            public string prgSvcId
            {
                get => prgSvcIdField;
                set => prgSvcIdField = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramSeason
        {
            private List<assetType> assetsField;

            private List<castTypeMember> castField;

            private List<crewTypeMember> crewField;

            private programsProgramSeasonDescriptions descriptionsField;

            private List<keywordsTypeKeyword> keywordsField;

            private List<string> officialURLField;

            private programsProgramSeasonOriginalNetwork originalNetworkField;

            private List<relationsTypeRelation> relationsField;

            private DateTime seasonFinaleField;

            private bool seasonFinaleFieldSpecified;

            private string seasonIdField;

            private string seasonNumberField;

            private DateTime seasonPremiereField;

            private bool seasonPremiereFieldSpecified;

            private string seasonYearField;

            private bool showcardField;

            private bool showcardFieldSpecified;

            private programsProgramSeasonTitles titlesField;

            private string totalSeasonEpisodesField;

            /// <remarks />
            [XmlElement(DataType = "date")]
            public DateTime seasonPremiere
            {
                get => seasonPremiereField;
                set => seasonPremiereField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool seasonPremiereSpecified
            {
                get => seasonPremiereFieldSpecified;
                set => seasonPremiereFieldSpecified = value;
            }

            /// <remarks />
            [XmlElement(DataType = "date")]
            public DateTime seasonFinale
            {
                get => seasonFinaleField;
                set => seasonFinaleField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool seasonFinaleSpecified
            {
                get => seasonFinaleFieldSpecified;
                set => seasonFinaleFieldSpecified = value;
            }

            /// <remarks />
            public programsProgramSeasonOriginalNetwork originalNetwork
            {
                get => originalNetworkField;
                set => originalNetworkField = value;
            }

            /// <remarks />
            [XmlElement(DataType = "positiveInteger")]
            public string totalSeasonEpisodes
            {
                get => totalSeasonEpisodesField;
                set => totalSeasonEpisodesField = value;
            }

            /// <remarks />
            [XmlElement("officialURL", DataType = "token")]
            public List<string> officialURL
            {
                get => officialURLField;
                set => officialURLField = value;
            }

            /// <remarks />
            public bool showcard
            {
                get => showcardField;
                set => showcardField = value;
            }

            /// <remarks />
            [XmlIgnore]
            public bool showcardSpecified
            {
                get => showcardFieldSpecified;
                set => showcardFieldSpecified = value;
            }

            /// <remarks />
            public programsProgramSeasonTitles titles
            {
                get => titlesField;
                set => titlesField = value;
            }

            /// <remarks />
            public programsProgramSeasonDescriptions descriptions
            {
                get => descriptionsField;
                set => descriptionsField = value;
            }

            /// <remarks />
            [XmlArrayItem("member", IsNullable = false)]
            public List<castTypeMember> cast
            {
                get => castField;
                set => castField = value;
            }

            /// <remarks />
            [XmlArrayItem("member", IsNullable = false)]
            public List<crewTypeMember> crew
            {
                get => crewField;
                set => crewField = value;
            }

            /// <remarks />
            [XmlArrayItem("keyword", IsNullable = false)]
            public List<keywordsTypeKeyword> keywords
            {
                get => keywordsField;
                set => keywordsField = value;
            }

            /// <remarks />
            [XmlArrayItem("relation", IsNullable = false)]
            public List<relationsTypeRelation> relations
            {
                get => relationsField;
                set => relationsField = value;
            }

            /// <remarks />
            [XmlArrayItem("asset", IsNullable = false)]
            public List<assetType> assets
            {
                get => assetsField;
                set => assetsField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "integer")]
            public string seasonNumber
            {
                get => seasonNumberField;
                set => seasonNumberField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string seasonId
            {
                get => seasonIdField;
                set => seasonIdField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "positiveInteger")]
            public string seasonYear
            {
                get => seasonYearField;
                set => seasonYearField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramSeasonOriginalNetwork
        {
            private string prgSvcIdField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "integer")]
            public string prgSvcId
            {
                get => prgSvcIdField;
                set => prgSvcIdField = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramSeasonTitles
        {
            private string langField;

            private List<titleDescType> titleField;

            /// <remarks />
            [XmlElement("title")]
            public List<titleDescType> title
            {
                get => titleField;
                set => titleField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "language")]
            public string lang
            {
                get => langField;
                set => langField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class programsProgramSeasonDescriptions
        {
            private List<titleDescType> descField;

            private string langField;

            /// <remarks />
            [XmlElement("desc")]
            public List<titleDescType> desc
            {
                get => descField;
                set => descField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "language")]
            public string lang
            {
                get => langField;
                set => langField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class keywordsTypeKeyword
        {
            private string typeField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string type
            {
                get => typeField;
                set => typeField = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class relationsTypeRelation
        {
            private string connectorTypeField;

            private string typeField;

            private string valueField;

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string type
            {
                get => typeField;
                set => typeField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string connectorType
            {
                get => connectorTypeField;
                set => connectorTypeField = value;
            }

            /// <remarks />
            [XmlText(DataType = "token")]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class relationshipsTypeRelationship
        {
            private string associationField;

            private string firstNameField;

            private string lastNameField;

            private string personIdField;

            private string personNameIdField;

            private string rootIdField;

            private List<string> tmsIdsField;

            private string typeField;

            /// <remarks />
            public string rootId
            {
                get => rootIdField;
                set => rootIdField = value;
            }

            /// <remarks />
            [XmlArrayItem("tmsId", IsNullable = false)]
            public List<string> tmsIds
            {
                get => tmsIdsField;
                set => tmsIdsField = value;
            }

            /// <remarks />
            public string personId
            {
                get => personIdField;
                set => personIdField = value;
            }

            /// <remarks />
            public string personNameId
            {
                get => personNameIdField;
                set => personNameIdField = value;
            }

            /// <remarks />
            public string firstName
            {
                get => firstNameField;
                set => firstNameField = value;
            }

            /// <remarks />
            public string lastName
            {
                get => lastNameField;
                set => lastNameField = value;
            }

            /// <remarks />
            public string type
            {
                get => typeField;
                set => typeField = value;
            }

            /// <remarks />
            public string association
            {
                get => associationField;
                set => associationField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class externalLinksTypeExternalLink
        {
            private string idField;

            private string scoreField;

            private string urlField;

            private string vendorField;

            private string vendorIdField;

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string vendor
            {
                get => vendorField;
                set => vendorField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string vendorId
            {
                get => vendorIdField;
                set => vendorIdField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string id
            {
                get => idField;
                set => idField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string url
            {
                get => urlField;
                set => urlField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string score
            {
                get => scoreField;
                set => scoreField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class videoDescriptorsTypeVideoDescriptor
        {
            private string idField;

            private string ordField;

            private string typeField;

            private string weightField;

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string id
            {
                get => idField;
                set => idField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string ord
            {
                get => ordField;
                set => ordField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string weight
            {
                get => weightField;
                set => weightField = value;
            }

            /// <remarks />
            [XmlAttribute(DataType = "token")]
            public string type
            {
                get => typeField;
                set => typeField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        [XmlRoot(Namespace = "", IsNullable = false)]
        public class programs
        {
            private List<programsProgram> programField;

            /// <remarks />
            [XmlElement("program")]
            public List<programsProgram> program
            {
                get => programField;
                set => programField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        [XmlRoot(Namespace = "", IsNullable = false)]
        public class requestParameters
        {
            private List<requestParametersRequestParameter> requestParameterField;

            /// <remarks />
            [XmlElement("requestParameter")]
            public List<requestParametersRequestParameter> requestParameter
            {
                get => requestParameterField;
                set => requestParameterField = value;
            }
        }

        /// <remarks />
        [GeneratedCode("xsd", "4.6.1590.0")]
        [SerializableAttribute]
        [DebuggerStepThrough]
        [DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public class requestParametersRequestParameter
        {
            private string nameField;

            private string valueField;

            /// <remarks />
            [XmlAttribute]
            public string name
            {
                get => nameField;
                set => nameField = value;
            }

            /// <remarks />
            [XmlText]
            public string Value
            {
                get => valueField;
                set => valueField = value;
            }
        }
    }
}