// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;
using System.Runtime.InteropServices;
using log4net.Config;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("SchTech File Manager")]
[assembly: AssemblyDescription("SCH Tech File Manager")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("SCH Tech Ltd")]
[assembly: AssemblyProduct("SchTech.File.Manager")]
[assembly: AssemblyCopyright("Copyright © SCH Tech Ltd 2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("f39ae7f9-3f7d-4942-bb7e-f6db58255042")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]


[assembly: AssemblyVersion("1.0.1.904")]
[assembly: AssemblyFileVersion("1.0.1.904")]
[assembly: XmlConfigurator(ConfigFile = "Config\\log4net.config")]
